FROM node:23-alpine3.21

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY ./ ./

ENV VITE_API_URL=http://195.15.204.225:3003

RUN npm run build

RUN npm install -g serve

COPY dist ./app/dist

EXPOSE 80

CMD ["serve", "-s", "dist", "-l", "80"]