services:
  db:
    image: postgres:18
    restart: always # Le conteneur redémarre dès que nécessaire
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # Mot de passe user psql
      - POSTGRES_USER=${POSTGRES_USER} # Nom utilisateur psql
      - POSTGRES_DB=${POSTGRES_DB} # Nom base de données

  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}
    depends_on:
      # `depends_on` indique à Docker d’attendre que le service db soit démarré,
      # mais cela n’établit pas de connexion entre les services.
      - db

  backend:
    restart: always
    build:
      context: backend # Indique le dossier dans lequel trouver le Dockerfile
    volumes:
      - ./backend:/app # Bind des fichiers locaux et ceux du conteneur
      - /app/node_modules # Exclusion du bind des node_modules locaux et ceux du conteneur
    environment:
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGHOST=${POSTGRES_HOST}
      - PGDATABASE=${POSTGRES_DB}
      - JWT_SECRET=${BACKEND_JWT_SECRET}
      - JWT_RT_TTL=${BACKEND_JWT_RT_TTL}
      - CORS_ALLOWED=${BACKEND_CORS_ALLOWED}
    ports:
      - ${BACKEND_PORT}
    depends_on:
      - db

  frontend:
    restart: always
    build:
      context: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${FRONTEND_VITE_API_URL}
    ports:
      - ${FRONTEND_PORT}